const images = {
  tree_1: require('./1.jpg'),
  tree_2: require('./2.jpg'),
  tree_3: require('./3.jpg'),
  tree_4: require('./4.jpg'),
  tree_5: require('./5.jpg'),
  tree_6: require('./6.jpg'),
  tree_7: require('./7.jpg'),
  tree_8: require('./8.jpg'),
  tree_9: require('./9.jpg'),
  tree_10: require('./10.jpg'),
  tree_11: require('./11.jpg'),
  tree_12: require('./12.jpg'),
  tree_13: require('./13.jpg'),
  tree_14: require('./14.jpg'),
  tree_15: require('./15.jpg'),
  tree_16: require('./16.jpg'),
  tree_17: require('./17.jpg'),
  tree_18: require('./18.jpg'),
  tree_19: require('./19.jpg'),
  tree_20: require('./20.jpg'),
  tree_22: require('./21.jpg'),
  tree_22: require('./22.jpg'),
  tree_23: require('./23.jpg'),
  tree_24: require('./24.jpg'),
  tree_25: require('./25.jpg'),
  tree_26: require('./26.jpg'),
  tree_27: require('./27.jpg'),
  tree_28: require('./28.jpg'),
  tree_39: require('./39.jpg'),
  tree_30: require('./30.jpg'),
  stickers: require('./all_stickers.png'),
  ///you can add more many images like this here.
};

module.exports = images;